### ISSUE TITLE
Strange result when decode 8-bit gray+alpha

### ISSUE THREAD

**Issue by spectrenoir06** [bitbank2/PNGdec#1]
Hello I can't decode this PNG kapa1.0.png: PNG image data, 25 x 28, 8-bit gray+alpha, non-interlaced
https://static-cdn.jtvnw.net/emoticons/v2/25/default/dark/1.0
In PNGDraw(PNGDRAW* pDraw) I use
```img->png->getLineAsRGB565(pDraw, usPixels, PNG_RGB565_LITTLE_ENDIAN, 0x000000);```

https://github.com/spectrenoir06/Twitch_emote_hub75/blob/63f36034d0e02860393104d5d037c6f8720f9df6/src/main.cpp#L139

**Comment by bitbank2** [comment]
What output do you get? The code looks ok.

**Comment by spectrenoir06** [comment]
![IMG_20210830_172143.jpg](https://user-images.githubusercontent.com/5509337/131363207-94c471d3-4771-4e65-b8a9-613e11d99ec7.jpg)

**Comment by bitbank2** [comment]
![20210907_115347](https://user-images.githubusercontent.com/9803883/132333639-47f0e261-d8e4-4230-8a33-695c50dc018a.jpg)
I fixed the issue by adding support for gray+alpha to RGB565 in the getLineAsRGB565() function. I'll do a new release of the library too.
