### ISSUE TITLE
subsistute code and FAR data types on ARM926EJS

### ISSUE THREAD

**Issue by 0x0fe** [bitbank2/PNGdec#18]
Trying to compile on ARM926EJS, in KEIL Uvision, in bare metal. I dont have **code** and **FAR** types, preventing compilation, how should these be sustituted?

![image](https://user-images.githubusercontent.com/89607149/223236374-511a238d-5c00-4868-9745-ab15e96e86f2.png)

**Comment by bitbank2** [comment]
That structure is from ZLIB, I didn't create it; I would take a look at that code base to see if anyone has a way to help you.
