### ISSUE TITLE
Memory usage increase

### ISSUE THREAD

**Issue by toine512** [bitbank2/PNGdec#24]
Hi Mr Bank,

I'm using PNGdec in my ESP-IDF project (ESP32-S3) with direct callback rendering.
With latest master code (a0f4b16) I noticed an increase of about 1.5 KiB in static memory consumption compared to commit 8abf6be (31 jan 2022).
Is that to be expected?

Thanks.

**Comment by bitbank2** [comment]
You can see why in the commit you referenced. I increased the line buffer to allow decoding of up to 480-wide 32-bit pixels. You're welcome to change your local copy to buffer fewer pixels if you're working with small images.
