### ISSUE TITLE
[RP2040, ARDUINO, PLATFORMIO] PNGDec decode causes infinite loop

### ISSUE THREAD

**Issue by basgoossen** [bitbank2/PNGdec#25]
**Describe the bug**
When running pngDEC with the example octocat files on a RP2040 (platformIO, both earlephilhower cora and pico core). the png header is read correctly, however a call to png.decode(nullptr, 0); results in an infinite loop (in zlib inflate). 

**To Reproduce**
1. Create a project in platform IO for the rp2040 (pico core or earlephilhower).
2. include PNGdec.h and an octocat.h file of preference.
3. call png.openRAM(octocat, len, drawPNGLine);
4. verify returned value to be 0 (PNG_SUCCESS);
5. run png.decode(nullptr,0);
6. Device will be stuck in an infinite loop from line: err = inflate(&d_stream, Z_NO_FLASH, iOptions & PNG_CHECK_CRC);

**Expected behavior**
The expected behaviour whould be that the png is decoded and for each line of image drawPNGLine is called.

**Image you're having trouble with**
example Octocat files from the PNGdec library.

**Comment by basgoossen** [comment]
Correction, it does not enter an infinite loop, it just crashes the RP2040. (infinite loop was created by adding debug lines and the omitted {} in the infinite for loop / switch loop in inflate.

**Comment by bitbank2** [comment]
I believe this is due to the RP2040 having an exception for unaligned pointer access. I think I regressed this code to undo that optimization. Clone the latest code instead of using the last release and see if it's resolved. If not, try removing 
"ALLOWS_UNALIGNED" from inffast.c

**Comment by basgoossen** [comment]
First of all thanks for your reply!
I've tested both proposed solutions, they however do not change the situation. The master in Github indeed is different from the library version that PlatformIO offers, but also the newer version (directly cloned from github) still causes the freeze in the same location. I'm actually quite confused why, since it seems like a pretty ligit write to a initialized pointer location.

**Comment by bitbank2** [comment]
Did you change the current code on Github to get it to work? When you say "removed the unaligned blocks" do you mean you disabled the #define or actually deleted the lines? The code on Github should work unchanged on your RP2040. If you confirm this, I'll do a new release.

**Comment by basgoossen** [comment]
Hi BitBank2,
First i removed the entire #ifdef blocks, but later i also tested removing the 2 occasions of:

#define ALLOWS_UNALIGNED

In both inflate.c and inffast.c, and i can confirm that the latter also works.

Thanks again for your efforts and for creating this tool.

**Comment by MagnusThome** [comment]
Any time schedule for a release with this fixed? 

This code example that is included with TFT_eSPI uses PNGdec and fails on rp2040:
https://github.com/Bodmer/TFT_eSPI/blob/master/examples/PNG%20Images/Flash_PNG/Flash_PNG.ino

**Comment by MagnusThome** [comment]
Downloaded the current code and it worked fine 👍👍👍

**Comment by bitbank2** [comment]
Great, thanks for testing. I'll do the release...
