### ISSUE TITLE
Fails to decode PNG files created by Windows Snipping tool

### ISSUE THREAD

**Issue by KurtE** [bitbank2/PNGdec#26]
**Describe the bug**
I have an image viewer that I use sort of for fun and also for developing/testing out different TFT display libraries.
I am finding that many of the PNG files I have tried with the display code fail to decode.   

The last couple of ones were ones that I created by using the Windows Snip program (Window+Shift+S) and choose the area I wish to capture, which brings up the snipping tool.  If I do a save operation and choose PNG as file format,  and then copy the file over to the SD card on my Teensy board (T4.1 or MMOD or one that I last tried on which is a Custom board...)  When the display code scans for the different files it then fails to display the image:

I only have a few PNG files on this board:
```
Loading PNG image 'raytrace.png'
image specs: (800 x 480), pixel type: 2 Bpp: 8 Alpha:0 Interlaced:0
Scale: 1/1 Image Offsets (112, 60)
!!File:raytrace.png Time:109 writeRect calls:480

Loading PNG image 'display_adapters.png'
image specs: (452 x 332), pixel type: 6 Bpp: 8 Alpha:1 Interlaced:0
Scale: 1/1 Image Offsets (286, 134)
Ping Decode returned error: 2 PNG_DECODE_ERROR
!!File:display_adapters.png Time:8 writeRect calls:0

Loop looking for image file

Loading PNG image 'Laiik-Clare.png'
image specs: (816 x 580), pixel type: 2 Bpp: 8 Alpha:0 Interlaced:0
Scale: 1/1 Image Offsets (104, 10)
!!File:Laiik-Clare.png Time:130 writeRect calls:580

Loading PNG image 'perf_small.png'
image specs: (1478 x 396), pixel type: 3 Bpp: 4 Alpha:0 Interlaced:0
Scale: 1/2 Image Offsets (142, 201)
Ping Decode returned error: 2 PNG_DECODE_ERROR
!!File:perf_small.png Time:8 writeRect calls:0
```
The first one raytrace.png worked.  Note: Originally when I created the file with the steps mentioned above. It failed to display it.
I then loaded the file in Photoshop elements, and then did a save as, and saved it again back as PNG.  I gave it the options for fast access (not compressed) and Not interlaced and now it displays.   This is also true for the third one... Laiik-Clare.png

The 2nd one display_adapters.png - was the latest one I created.  Which failed with PNG_DECODE_ERROR.

Note: I tried to copy down a PNG file where another forum member post had PNG files, which I am assuming that was done using the Windows Snipping tool as well, and those also failed to load

**To Reproduce**
I think mostly covered above.

**Expected behavior**
Hoping that it can decide those files.

**Image you're having trouble with**
If applicable, add original image files to help explain your problem.
![display_adapters](https://github.com/user-attachments/assets/7968c149-720d-4132-8c70-a2673cb18464)

**Additional context**
Here is one that worked after I resaved it.
![raytrace](https://github.com/user-attachments/assets/dfcd7b5c-1b35-4f0c-9cff-789a892fdfbe)

Running Windows 11
Nightly build of Arduino 2.x
PngDec version 1.0.2

**Comment by bitbank2** [comment]
Thanks for reporting the error. Can you email me the images which fail? Send to bitbank@pobox.com.
Sharing them in Github doesn't guarantee that the browser won't modify the images.

**Comment by bitbank2** [comment]
I just tried your failing image and it decodes correctly for me. Are you using the latest version of the library? Can you share the code you're using to read/decode the images?

**Comment by KurtE** [comment]
email sent, also included zip file of sketch and the like.

I renamed the 1.0.2 version that the library manager downloaded and linked in the 
github version and it looks like it is now happy with these PNG files.

So you can probably close out this.  and/or maybe release the current stuff?

Thanks
